language: node_js
install:
- npm install
script: npm test
deploy:
  provider: openshift
  server: https://c100-e.eu-gb.containers.cloud.ibm.com:32698/
  project: tomsherlocked-nodejs-ex
  edge: true
env:
  global:
    secure: wLJ7Oc2oumY2/lU2LPqXXKJ8zA6DDTscqTn8zt5/DzlZrjQBWdE0WXdsrSufqXRBcR44YOHdNMZZguq3Sx0ctee8sgHrMsAN/Qj6ee/6J4E9+fWDmfk9A3OMdW26NxrwU6ygYDchgdLgAOl8uO36T7gIr+mvXM63gJlP2U+/8FC0PBrhZI0QapBVGGsmqlCuic/6w9Vxa55kuFhB6UKyO8Sz/Hdoug0DfyVGr7DDCUYEZRzqoRNZAwDTdPZMil2XjikEwxPcRDB8k7LKqqorALR4il218xxR2lguvlLQIl62qYk67NPW3sgTn26D7iM5/dr/et6dafMGybQYj6ZEJkzqEBcnjdyuTG5/iB0dSkucpCapO2kDG3s0td9+xiQdp0rELuSczk4O1JpUNGnGknhOs7w5vOkfY5kS9CfVlX+19C+zcnsExNKBukf5PXZt6xLrBaJvGdMDET4B10S3MUrUrp3ODZFQ2fcLz3cHw1zhpCAX9Kiaw3Wq24XzYDgswsqE/cY2dJx6AO1D69MvQ47doVUVr2mnqwKSf1wa6+TmIdjBnFoPbCudYBZPly98wbZ6uC//soFWJonrYOdzcjpCM6D2+KNemRPnh+K69k02utqxhMpwxxmfWSvg2x1c/8s95wrcx9hcly1UDKbPuhMuilXz40NskiPu9ajbLtk=
